<?php
namespace yii\easyii\modules\news\api;

use Yii;
use yii\data\ActiveDataProvider;
use yii\easyii\models\Tag;
use yii\easyii\widgets\Fancybox;
use yii\helpers\VarDumper;
use yii\widgets\LinkPager;

use yii\easyii\modules\news\models\News as NewsModel;

/**
 * News module API
 * @package yii\easyii\modules\news\api
 *
 * @method static NewsObject get(array $params) Get news object by id or slug
 * @method static array items(array $options = []) Get list of news as NewsObject objects
 * @method static mixed last(int $limit = 1) Get last news
 * @method static void plugin() Applies FancyBox widget on photos called by box() function
 * @method static string pages() returns pagination html generated by yii\widgets\LinkPager widget.
 * @method static \stdClass pagination() returns yii\data\Pagination object.
 */

class News extends \yii\easyii\components\API
{
    private $_adp;
    private $_last;
    private $_items;
    private $_item = [];

    public function api_items($options = [])
    {
        if(!$this->_items){
            $this->_items = [];

            $with = ['seo'];
            if(Yii::$app->getModule('admin')->activeModules['news']->settings['enableTags']){
                $with[] = 'tags';
            }
            $query = NewsModel::find()->with($with)->andWhere(['status' => NewsModel::STATUS_ON]);

            if(!empty($options['where'])) {
                $query->andFilterWhere($options['where']);
            }
            if(!empty($options['tags'])){
                $query
                    ->innerJoinWith('tags', false)
                    ->andWhere([Tag::tableName() . '.name' => (new NewsModel)->filterTagValues($options['tags'])])
                    ->addGroupBy('news_id');
            }

            if(!empty($options['language'])){
                $query->localized($options['language']);
            }
            
            if(!empty($options['orderBy'])){
                $query->orderBy($options['orderBy']);
            } else {
                $query->orderBy('time DESC');
            }

            if(!empty($options['limit'])){
                $query->limit($options['limit']);
            }

            $this->_adp = new ActiveDataProvider([
                'query' => $query,
                'pagination' => !empty($options['pagination']) ? $options['pagination'] : false
            ]);

            foreach($this->_adp->models as $model){
                $this->_items[] = new NewsObject($model);
            }
        }
        return $this->_items;
    }

    public function api_get($params)
    {
        if(!isset($this->_item[$params[0]])) {
            $this->_item[$params[0]] = $this->findNews($params);
        }
        return $this->_item[$params[0]];
    }

    public function api_last($limit = 1)
    {
        if($limit === 1 && $this->_last){
            return $this->_last;
        }

        $with = ['seo'];
        if(Yii::$app->getModule('admin')->activeModules['news']->settings['enableTags']){
            $with[] = 'tags';
        }

        $result = [];
        foreach(NewsModel::find()->with($with)->where(['status' => NewsModel::STATUS_ON])->limit($limit)->all() as $item){
            $result[] = new NewsObject($item);
        }

        if($limit > 1){
            return $result;
        }

        $this->_last = count($result) ? $result[0] : null;
        return $this->_last;
    }

    public function api_plugin($options = [])
    {
        Fancybox::widget([
            'selector' => '.easyii-box',
            'options' => $options
        ]);
    }

    public function api_pagination()
    {
        return $this->_adp ? $this->_adp->pagination : null;
    }

    public function api_pages()
    {
        return $this->_adp ? LinkPager::widget(['pagination' => $this->_adp->pagination]) : '';
    }

    private function findNews($params)
    {
        $news = NewsModel::find()->where(['or', 'news_id=:id_slug', 'slug=:id_slug'], [':id_slug' => $params[0]])->andWhere(['status' => NewsModel::STATUS_ON]);

        if(isset($params[1])) {
            $news->localized($params[1]);
        }

        $news = $news->one();

        if($news) {
            $news->updateCounters(['views' => 1]);
            return new NewsObject($news);
        } else {
            return null;
        }
    }
}